/* Browser-only document utilities. No network requests are made with user files. */
if(window.pdfjsLib) pdfjsLib.GlobalWorkerOptions.workerSrc='/vendor/pdfjs-worker-3.11.174.min.js';

const DOC_TOOLS=[
  {group:'Organize PDFs',id:'merge',name:'Merge PDFs',description:'Combine complete PDF files in the order shown.',accept:'.pdf',multiple:true},
  {group:'Organize PDFs',id:'split',name:'Split PDF',description:'Create individual PDF files for selected pages.',accept:'.pdf'},
  {group:'Organize PDFs',id:'extract',name:'Extract pages',description:'Create a new PDF containing selected pages.',accept:'.pdf'},
  {group:'Organize PDFs',id:'delete',name:'Delete pages',description:'Remove selected pages and keep the remainder.',accept:'.pdf'},
  {group:'Organize PDFs',id:'reorder',name:'Reorder pages',description:'Build a PDF in the page order you enter.',accept:'.pdf'},
  {group:'Organize PDFs',id:'rotate',name:'Rotate pages',description:'Rotate selected pages by 90, 180 or 270 degrees.',accept:'.pdf'},
  {group:'Organize PDFs',id:'duplicate',name:'Duplicate pages',description:'Insert extra copies of selected pages.',accept:'.pdf'},
  {group:'Organize PDFs',id:'combine',name:'Combine selected pages',description:'Combine chosen pages from multiple PDFs.',accept:'.pdf',multiple:true},
  {group:'Convert to PDF',id:'image-to-pdf',name:'Image to PDF',description:'Arrange JPG, PNG or WebP images into one PDF.',accept:'image/jpeg,image/png,image/webp',multiple:true},
  {group:'Convert to PDF',id:'word-to-pdf',name:'Word to PDF',description:'Preview and convert a modern DOCX file in the browser.',accept:'.docx'},
  {group:'Convert to PDF',id:'text-to-pdf',name:'Text to PDF',description:'Turn plain text into a paginated PDF.',accept:'.txt'},
  {group:'Convert to PDF',id:'html-to-pdf',name:'HTML to PDF',description:'Render an HTML file or pasted HTML to PDF.',accept:'.html,.htm,text/html'},
  {group:'PDF to images',id:'pdf-to-jpg',name:'PDF to JPG',description:'Render every PDF page to an individual JPG.',accept:'.pdf'},
  {group:'PDF to images',id:'pdf-to-png',name:'PDF to PNG',description:'Render every PDF page to an individual PNG.',accept:'.pdf'},
  {group:'Compress',id:'pdf-compress',name:'PDF Compressor',description:'Rasterize and rebuild a PDF using selected quality and resolution.',accept:'.pdf'},
  {group:'Compress',id:'image-compress',name:'Image Compressor',description:'Resize or recompress JPG, PNG and WebP images.',accept:'image/jpeg,image/png,image/webp',multiple:true}
];

const list=document.querySelector('#document-tool-list'),panel=document.querySelector('#document-panel');
const state={tool:null,files:[],urls:[],cancelled:false,docxReady:false};
const bytes=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(2)} MB`;
const safeName=name=>name.replace(/[^a-z0-9._-]+/gi,'-').replace(/^-|-$/g,'')||'output';
const pageTools=['split','extract','delete','reorder','rotate','duplicate'];

function clearUrls(){state.urls.forEach(URL.revokeObjectURL);state.urls=[]}
function setTool(id){clearUrls();state.tool=DOC_TOOLS.find(t=>t.id===id)||DOC_TOOLS[0];state.files=[];state.cancelled=false;state.docxReady=false;const url=new URL(location.href);url.searchParams.set('tool',state.tool.id);history.replaceState({},'',url);renderList();renderPanel()}
function renderList(){list.querySelectorAll('button,[data-group]').forEach(x=>x.remove());let group='';for(const tool of DOC_TOOLS){if(group!==tool.group){group=tool.group;const heading=document.createElement('span');heading.dataset.group='';heading.className='resource-nav-label';heading.textContent=group;list.append(heading)}const button=document.createElement('button');button.type='button';button.className=tool.id===state.tool?.id?'active':'';button.textContent=tool.name;button.addEventListener('click',()=>setTool(tool.id));list.append(button)}}

function settingsMarkup(id){
  if(['split','extract','delete','reorder','rotate','duplicate','combine'].includes(id))return `<div class="settings-grid"><div class="field"><label for="pages">${id==='reorder'?'New page order':id==='combine'?'Selections by file':'Pages or ranges'}</label><input id="pages" value="${id==='combine'?'1:1-2, 2:1':'1-2, 4'}" placeholder="${id==='combine'?'1:1-2, 2:3':'1-3, 5'}"><small>${id==='combine'?'Use file number:pages. Example 1:1-2, 2:4':'Use commas and ranges. Example: 1-3, 5.'}</small></div>${id==='rotate'?'<div class="field"><label for="angle">Rotation</label><select id="angle"><option>90</option><option>180</option><option>270</option></select></div>':''}</div>`;
  if(id==='image-to-pdf')return `<div class="settings-grid"><div class="field"><label for="page-size">Page size</label><select id="page-size"><option value="a4">A4</option><option value="letter">Letter</option><option value="original">Original image size</option></select></div><div class="field"><label for="orientation">Orientation</label><select id="orientation"><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></div><div class="field"><label for="margin">Page margin (mm)</label><input id="margin" type="number" min="0" value="10"></div><div class="field"><label for="placement">Image placement</label><select id="placement"><option value="fit">Fit within page</option><option value="fill">Fill page and crop</option><option value="original">Original size</option></select></div><div class="field"><label for="quality">Image quality</label><input id="quality" type="range" min="40" max="100" value="90"><small>90%</small></div></div>`;
  if(id==='word-to-pdf')return `<div class="settings-grid"><div class="field"><label for="page-size">Page size</label><select id="page-size"><option value="a4">A4</option><option value="letter">Letter</option></select></div><div class="field"><label for="orientation">Orientation</label><select id="orientation"><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></div><div class="field"><label for="margin">Margin (mm)</label><input id="margin" type="number" min="0" value="12"></div></div><div class="disclaimer-box">Complex Word layouts, advanced fields, embedded objects and unusual fonts may not reproduce exactly in browser-based conversion.</div><div id="docx-preview" class="docx-preview" hidden></div>`;
  if(id==='text-to-pdf')return `<div class="settings-grid"><div class="field"><label for="page-size">Page size</label><select id="page-size"><option value="a4">A4</option><option value="letter">Letter</option></select></div><div class="field"><label for="orientation">Orientation</label><select id="orientation"><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></div></div><div class="field"><label for="source-text">Text</label><textarea id="source-text" rows="14" placeholder="Type or load a .txt file"></textarea></div>`;
  if(id==='html-to-pdf')return `<div class="settings-grid"><div class="field"><label for="page-size">Page size</label><select id="page-size"><option value="a4">A4</option><option value="letter">Letter</option></select></div><div class="field"><label for="orientation">Orientation</label><select id="orientation"><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></div></div><div class="field"><label for="source-html">HTML source</label><textarea id="source-html" rows="12" placeholder="<h1>Document</h1><p>Content…</p>"></textarea></div><div id="html-preview" class="docx-preview" hidden></div>`;
  if(['pdf-to-jpg','pdf-to-png'].includes(id))return `<div class="settings-grid"><div class="field"><label for="image-scale">Output resolution</label><select id="image-scale"><option value="1.5">Standard</option><option value="2" selected>High</option><option value="3">Very high</option></select></div>${id==='pdf-to-jpg'?'<div class="field"><label for="quality">JPG quality</label><input id="quality" type="range" min="40" max="100" value="90"></div>':''}</div>`;
  if(id==='pdf-compress')return `<div class="settings-grid"><div class="field"><label for="compression-mode">Compression mode</label><select id="compression-mode"><option value="light">Light</option><option value="balanced" selected>Balanced</option><option value="strong">Strong</option><option value="custom">Custom</option></select></div><div class="field"><label for="quality">Image quality</label><input id="quality" type="range" min="30" max="95" value="72"><small>72%</small></div><div class="field"><label for="resolution">Render resolution (DPI)</label><input id="resolution" type="number" min="72" max="200" value="120"></div><div class="field"><label><input id="remove-metadata" type="checkbox" checked> Remove metadata when rebuilding</label></div></div><div class="disclaimer-box">Compression rebuilds pages as readable images. Searchable text, links, forms, signatures and vector structure will not be retained. Some already optimized PDFs may become larger.</div>`;
  if(id==='image-compress')return `<div class="settings-grid"><div class="field"><label for="quality">Quality</label><input id="quality" type="range" min="20" max="100" value="80"><small>80%</small></div><div class="field"><label for="output-format">Output format</label><select id="output-format"><option value="image/jpeg">JPG</option><option value="image/webp">WebP</option><option value="image/png">PNG</option></select></div><div class="field"><label for="target-width">Maximum width (px, optional)</label><input id="target-width" type="number" min="1" placeholder="Keep original"></div><div class="field"><label for="target-height">Maximum height (px, optional)</label><input id="target-height" type="number" min="1" placeholder="Keep original"></div><div class="field"><label><input id="preserve-ratio" type="checkbox" checked> Preserve aspect ratio</label></div></div><div class="disclaimer-box">PNG is lossless; meaningful reduction may require smaller dimensions, palette reduction, or conversion to JPG/WebP. Metadata is removed when the canvas creates the output.</div>`;
  return '';
}

function renderPanel(){const t=state.tool;panel.innerHTML=`<p class="eyebrow">${t.group}</p><h2>${t.name}</h2><p class="tool-note">${t.description}</p><div class="privacy-strip"><strong>Local processing</strong><span>Your files remain on this device and are processed in your browser. Files are not retained after refresh or closing this page.</span></div><label class="upload-zone" id="upload-zone"><strong>Choose ${t.multiple?'files':'a file'} or drop ${t.multiple?'them':'it'} here</strong><p>Supported: ${t.accept}. Practical limit depends on your browser memory.</p><input id="file-input" type="file" accept="${t.accept}" ${t.multiple?'multiple':''}></label><div class="file-queue" id="file-queue"></div>${settingsMarkup(t.id)}<p class="tool-error" id="operation-error" role="alert"></p><div class="operation-progress" hidden><span></span></div><div class="tool-actions"><button type="button" id="process">${t.id==='word-to-pdf'?'Preview document':'Process files'}</button><button type="button" class="secondary" id="cancel" hidden>Cancel</button><button type="button" class="secondary" id="start-over">Start over</button></div><div id="operation-result"></div>`;
  const input=panel.querySelector('#file-input'),zone=panel.querySelector('#upload-zone');input.addEventListener('change',()=>addFiles([...input.files]));['dragenter','dragover'].forEach(e=>zone.addEventListener(e,event=>{event.preventDefault();zone.classList.add('dragging')}));['dragleave','drop'].forEach(e=>zone.addEventListener(e,event=>{event.preventDefault();zone.classList.remove('dragging')}));zone.addEventListener('drop',event=>addFiles([...event.dataTransfer.files]));panel.querySelector('#process').addEventListener('click',process);panel.querySelector('#cancel').addEventListener('click',()=>{state.cancelled=true});panel.querySelector('#start-over').addEventListener('click',()=>{clearUrls();state.files=[];state.docxReady=false;renderPanel()});panel.querySelectorAll('input[type="range"]').forEach(r=>r.addEventListener('input',()=>{const s=r.nextElementSibling;if(s?.tagName==='SMALL')s.textContent=`${r.value}%`}));panel.querySelector('#compression-mode')?.addEventListener('change',event=>{const presets={light:[85,160],balanced:[72,120],strong:[50,90]};if(presets[event.target.value]){panel.querySelector('#quality').value=presets[event.target.value][0];panel.querySelector('#quality').dispatchEvent(new Event('input'));panel.querySelector('#resolution').value=presets[event.target.value][1]}})
}

async function addFiles(files){const accepted=[];for(const file of files){if(file.size===0){showError(`${file.name} is empty.`);continue}if(state.files.some(x=>x.file.name===file.name&&x.file.size===file.size&&x.file.lastModified===file.lastModified)){showError(`${file.name} is already in the queue.`);continue}if(!state.tool.multiple&&state.files.length+accepted.length){showError('This tool accepts one file at a time.');break}accepted.push({file,meta:'Inspecting…'})}state.files.push(...accepted);renderQueue();for(const item of accepted){try{if(item.file.type==='application/pdf'||item.file.name.toLowerCase().endsWith('.pdf')){const pdf=await pdfjsLib.getDocument({data:await item.file.arrayBuffer()}).promise;item.meta=`${bytes(item.file.size)} · ${pdf.numPages} page${pdf.numPages===1?'':'s'}`;pdf.destroy()}else if(item.file.type.startsWith('image/')){const img=await loadImage(item.file);item.meta=`${bytes(item.file.size)} · ${img.naturalWidth} × ${img.naturalHeight}px`;URL.revokeObjectURL(img.src)}else item.meta=bytes(item.file.size)}catch(error){item.meta=`${bytes(item.file.size)} · Unable to inspect (${friendlyError(error)})`}renderQueue()}if(['text-to-pdf','html-to-pdf'].includes(state.tool.id)&&accepted[0]){const text=await accepted[0].file.text();const box=panel.querySelector(state.tool.id==='text-to-pdf'?'#source-text':'#source-html');if(box)box.value=text}}
function renderQueue(){const queue=panel.querySelector('#file-queue');if(!queue)return;queue.innerHTML=state.files.map((item,i)=>`<div class="file-row"><div><strong>${escapeHtml(item.file.name)}</strong><small>${item.meta}</small></div><div class="file-row-actions"><button type="button" data-up="${i}" aria-label="Move ${escapeHtml(item.file.name)} up">↑</button><button type="button" data-down="${i}" aria-label="Move ${escapeHtml(item.file.name)} down">↓</button><button type="button" data-remove="${i}" aria-label="Remove ${escapeHtml(item.file.name)}">×</button></div></div>`).join('');queue.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{state.files.splice(Number(b.dataset.remove),1);renderQueue()}));queue.querySelectorAll('[data-up]').forEach(b=>b.addEventListener('click',()=>move(Number(b.dataset.up),-1)));queue.querySelectorAll('[data-down]').forEach(b=>b.addEventListener('click',()=>move(Number(b.dataset.down),1)))}
function move(i,d){const j=i+d;if(j<0||j>=state.files.length)return;[state.files[i],state.files[j]]=[state.files[j],state.files[i]];renderQueue()}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function sanitizeHtml(source){const parsed=new DOMParser().parseFromString(source,'text/html');parsed.querySelectorAll('script,iframe,object,embed,link,meta').forEach(node=>node.remove());parsed.querySelectorAll('*').forEach(node=>{for(const attribute of [...node.attributes]){const name=attribute.name.toLowerCase(),value=attribute.value.trim();if(name.startsWith('on')||/^javascript:/i.test(value)||(['src','href'].includes(name)&&(/^(?:https?:)?\/\//i.test(value)||/^data:(?!image\/)/i.test(value))))node.removeAttribute(attribute.name)}});return parsed.body.innerHTML}
function showError(message){const e=panel.querySelector('#operation-error');if(e)e.textContent=message}
function friendlyError(error){const m=String(error?.message||error);if(/password/i.test(m))return 'Password-protected PDFs are not supported';if(/memory|allocation/i.test(m))return 'The browser did not have enough memory';if(/invalid|corrupt|xref/i.test(m))return 'The file may be corrupted or unsupported';return m.slice(0,180)}
function progress(n){const box=panel.querySelector('.operation-progress'),bar=box?.querySelector('span');if(box){box.hidden=false;bar.style.width=`${Math.max(0,Math.min(100,n))}%`}}
const yieldFrame=()=>new Promise(resolve=>requestAnimationFrame(resolve));
function checkCancelled(){if(state.cancelled)throw new Error('Operation cancelled.')}
function parsePages(text,count){const out=[];for(const part of text.split(',').map(x=>x.trim()).filter(Boolean)){const [a,b]=part.split('-').map(Number);if(!Number.isInteger(a)||a<1||a>count||b!==undefined&&(!Number.isInteger(b)||b<a||b>count))throw new Error(`Page selection “${part}” is outside 1–${count}.`);for(let n=a;n<=(b||a);n++)out.push(n-1)}return out}
function loadImage(file){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('The image could not be decoded.'));img.src=URL.createObjectURL(file)})}
function blobUrl(blob){const url=URL.createObjectURL(blob);state.urls.push(url);return url}
function downloadCard(blob,name,details){const url=blobUrl(blob);return `<div class="result-summary"><h3>Ready to download</h3><p>${details}</p><a class="tool-button" href="${url}" download="${safeName(name)}">Download ${escapeHtml(name)}</a></div>`}

async function process(){state.cancelled=false;showError('');panel.querySelector('#operation-result').innerHTML='';if(!state.files.length&&!['text-to-pdf','html-to-pdf'].includes(state.tool.id)){showError('Add at least one supported file before processing.');return}panel.querySelector('#cancel').hidden=false;panel.querySelector('#process').disabled=true;try{const id=state.tool.id;if(['merge','split','extract','delete','reorder','rotate','duplicate','combine'].includes(id))await organizePdf(id);else if(id==='image-to-pdf')await imagesToPdf();else if(id==='word-to-pdf')await wordToPdf();else if(id==='text-to-pdf')await textToPdf();else if(id==='html-to-pdf')await htmlToPdf();else if(id==='pdf-to-jpg'||id==='pdf-to-png')await pdfToImages(id);else if(id==='pdf-compress')await compressPdf();else if(id==='image-compress')await compressImages();}catch(error){showError(friendlyError(error))}finally{panel.querySelector('#process').disabled=false;panel.querySelector('#cancel').hidden=true}}

async function organizePdf(id){const {PDFDocument,degrees}=PDFLib;if(id==='merge'){const out=await PDFDocument.create();for(let i=0;i<state.files.length;i++){checkCancelled();const src=await PDFDocument.load(await state.files[i].file.arrayBuffer());const pages=await out.copyPages(src,src.getPageIndices());pages.forEach(p=>out.addPage(p));progress((i+1)/state.files.length*90);await yieldFrame()}const bytesOut=await out.save();panel.querySelector('#operation-result').innerHTML=downloadCard(new Blob([bytesOut],{type:'application/pdf'}),'merged.pdf',`${out.getPageCount()} pages · ${bytes(bytesOut.length)}`);progress(100);return}
  if(id==='combine'){const out=await PDFDocument.create(),spec=panel.querySelector('#pages').value.split(',').map(x=>x.trim()).filter(Boolean);for(let s=0;s<spec.length;s++){checkCancelled();const match=spec[s].match(/^(\d+):(.*)$/);if(!match)throw new Error('Use file number:pages, for example 1:1-2, 2:4.');const fileIndex=Number(match[1])-1;if(!state.files[fileIndex])throw new Error(`File ${fileIndex+1} is not in the queue.`);const src=await PDFDocument.load(await state.files[fileIndex].file.arrayBuffer()),indices=parsePages(match[2],src.getPageCount()),pages=await out.copyPages(src,indices);pages.forEach(p=>out.addPage(p));progress((s+1)/spec.length*90)}const bytesOut=await out.save();panel.querySelector('#operation-result').innerHTML=downloadCard(new Blob([bytesOut],{type:'application/pdf'}),'combined-pages.pdf',`${out.getPageCount()} selected pages · ${bytes(bytesOut.length)}`);progress(100);return}
  const src=await PDFDocument.load(await state.files[0].file.arrayBuffer()),count=src.getPageCount(),indices=parsePages(panel.querySelector('#pages').value,count);if(!indices.length)throw new Error('Select at least one page.');if(id==='split'){const zip=new JSZip();for(let i=0;i<indices.length;i++){checkCancelled();const out=await PDFDocument.create(),[page]=await out.copyPages(src,[indices[i]]);out.addPage(page);zip.file(`page-${indices[i]+1}.pdf`,await out.save());progress((i+1)/indices.length*90);await yieldFrame()}const blob=await zip.generateAsync({type:'blob'});panel.querySelector('#operation-result').innerHTML=downloadCard(blob,'split-pages.zip',`${indices.length} individual PDF files · ${bytes(blob.size)}`);progress(100);return}
  const selected=new Set(indices),order=id==='reorder'?indices:id==='delete'?src.getPageIndices().filter(i=>!selected.has(i)):src.getPageIndices();if(id==='delete'&&order.length===0)throw new Error('At least one page must remain.');if(id==='extract')order.splice(0,order.length,...indices);if(id==='duplicate'){order.splice(0,order.length);for(const i of src.getPageIndices()){order.push(i);if(selected.has(i))order.push(i)}}const out=await PDFDocument.create(),pages=await out.copyPages(src,order);pages.forEach((p,i)=>{if(id==='rotate'&&selected.has(order[i]))p.setRotation(degrees(Number(panel.querySelector('#angle').value)));out.addPage(p)});const output=await out.save();panel.querySelector('#operation-result').innerHTML=downloadCard(new Blob([output],{type:'application/pdf'}),`${id}-output.pdf`,`${out.getPageCount()} pages · ${bytes(output.length)}`);progress(100)}

async function imagesToPdf(){const {jsPDF}=window.jspdf,format=panel.querySelector('#page-size').value,orientation=panel.querySelector('#orientation').value,margin=numVal('#margin',10),placement=panel.querySelector('#placement').value,quality=numVal('#quality',90)/100;let doc=null;for(let i=0;i<state.files.length;i++){checkCancelled();const img=await loadImage(state.files[i].file),original=format==='original',pageFormat=original?[img.naturalWidth*.264583,img.naturalHeight*.264583]:format;const next=new jsPDF({orientation,unit:'mm',format:pageFormat,compress:true});if(!doc)doc=next;else doc.addPage(pageFormat,orientation);const pw=doc.internal.pageSize.getWidth(),ph=doc.internal.pageSize.getHeight(),availW=pw-margin*2,availH=ph-margin*2,ratio=img.naturalWidth/img.naturalHeight;let w=availW,h=w/ratio;if(placement==='fill'&&h<availH){h=availH;w=h*ratio}else if(placement==='fit'&&h>availH){h=availH;w=h*ratio}else if(placement==='original'){w=Math.min(availW,img.naturalWidth*.264583);h=w/ratio}const x=(pw-w)/2,y=(ph-h)/2,canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;canvas.getContext('2d').drawImage(img,0,0);doc.addImage(canvas.toDataURL('image/jpeg',quality),'JPEG',x,y,w,h);URL.revokeObjectURL(img.src);progress((i+1)/state.files.length*90);await yieldFrame()}const blob=doc.output('blob');panel.querySelector('#operation-result').innerHTML=downloadCard(blob,'images.pdf',`${state.files.length} image page${state.files.length===1?'':'s'} · ${bytes(blob.size)}`);progress(100)}

async function wordToPdf(){const preview=panel.querySelector('#docx-preview'),button=panel.querySelector('#process');if(!state.docxReady){preview.hidden=false;preview.innerHTML='';await docx.renderAsync(await state.files[0].file.arrayBuffer(),preview,null,{inWrapper:true,ignoreWidth:false,ignoreHeight:false,breakPages:true});state.docxReady=true;button.textContent='Generate PDF from preview';panel.querySelector('#operation-result').innerHTML='<div class="result-summary"><h3>Preview ready</h3><p>Review the browser-rendered document above. If it is acceptable, generate the PDF.</p></div>';progress(100);return}const {jsPDF}=window.jspdf,orientation=panel.querySelector('#orientation').value,format=panel.querySelector('#page-size').value,margin=numVal('#margin',12),sections=[...preview.querySelectorAll('section')];if(!sections.length)sections.push(preview);const pdf=new jsPDF({orientation,unit:'mm',format});for(let i=0;i<sections.length;i++){checkCancelled();if(i)pdf.addPage(format,orientation);const canvas=await html2canvas(sections[i],{scale:1.6,backgroundColor:'#ffffff',useCORS:true}),pw=pdf.internal.pageSize.getWidth()-margin*2,ph=canvas.height*pw/canvas.width;pdf.addImage(canvas.toDataURL('image/jpeg',.9),'JPEG',margin,margin,pw,Math.min(ph,pdf.internal.pageSize.getHeight()-margin*2));progress((i+1)/sections.length*90);await yieldFrame()}const blob=pdf.output('blob');panel.querySelector('#operation-result').innerHTML=downloadCard(blob,'word-converted.pdf',`${sections.length} rendered page${sections.length===1?'':'s'} · ${bytes(blob.size)}`);progress(100)}
async function textToPdf(){const {jsPDF}=window.jspdf,pdf=new jsPDF({orientation:panel.querySelector('#orientation').value,unit:'mm',format:panel.querySelector('#page-size').value}),text=panel.querySelector('#source-text').value;if(!text.trim())throw new Error('Enter or load text before generating the PDF.');const margin=15,width=pdf.internal.pageSize.getWidth()-30,lines=pdf.splitTextToSize(text,width),lineHeight=6;let y=margin;for(const line of lines){if(y>pdf.internal.pageSize.getHeight()-margin){pdf.addPage();y=margin}pdf.text(line,margin,y);y+=lineHeight}const blob=pdf.output('blob');panel.querySelector('#operation-result').innerHTML=downloadCard(blob,'text.pdf',`${pdf.getNumberOfPages()} pages · ${bytes(blob.size)}`);progress(100)}
async function htmlToPdf(){const source=panel.querySelector('#source-html').value;if(!source.trim())throw new Error('Enter or load HTML before generating the PDF.');const preview=panel.querySelector('#html-preview');preview.hidden=false;preview.innerHTML=sanitizeHtml(source);const canvas=await html2canvas(preview,{scale:1.5,backgroundColor:'#fff'}),{jsPDF}=window.jspdf,pdf=new jsPDF({orientation:panel.querySelector('#orientation').value,unit:'mm',format:panel.querySelector('#page-size').value}),margin=10,pw=pdf.internal.pageSize.getWidth()-20,ph=canvas.height*pw/canvas.width,pageH=pdf.internal.pageSize.getHeight()-20,img=canvas.toDataURL('image/jpeg',.9);let remaining=ph,offset=0;while(remaining>0){if(offset)pdf.addPage();pdf.addImage(img,'JPEG',margin,margin-offset,pw,ph);remaining-=pageH;offset+=pageH}const blob=pdf.output('blob');panel.querySelector('#operation-result').innerHTML=downloadCard(blob,'html.pdf',`${pdf.getNumberOfPages()} pages · ${bytes(blob.size)}`);progress(100)}

async function pdfToImages(id){const pdf=await pdfjsLib.getDocument({data:await state.files[0].file.arrayBuffer()}).promise,zip=new JSZip(),previews=[],scale=numVal('#image-scale',2),quality=numVal('#quality',90)/100,mime=id==='pdf-to-png'?'image/png':'image/jpeg',ext=id==='pdf-to-png'?'png':'jpg';for(let i=1;i<=pdf.numPages;i++){checkCancelled();const page=await pdf.getPage(i),viewport=page.getViewport({scale}),canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;const blob=await new Promise(r=>canvas.toBlob(r,mime,quality));zip.file(`page-${i}.${ext}`,blob);if(i<=6)previews.push(blobUrl(blob));canvas.width=canvas.height=1;progress(i/pdf.numPages*88);await yieldFrame()}const output=await zip.generateAsync({type:'blob'},m=>progress(88+m.percent*.12));panel.querySelector('#operation-result').innerHTML=`${downloadCard(output,`pdf-pages-${ext}.zip`,`${pdf.numPages} rendered images · ${bytes(output.size)}`)}<div class="preview-grid">${previews.map((u,i)=>`<figure><img src="${u}" alt="Preview of page ${i+1}"><figcaption>Page ${i+1}</figcaption></figure>`).join('')}</div>`;pdf.destroy();progress(100)}

async function compressPdf(){
  const original=state.files[0].file;
  const pdf=await pdfjsLib.getDocument({data:await original.arrayBuffer()}).promise;
  const {jsPDF}=window.jspdf,quality=numVal('#quality',72)/100,dpi=numVal('#resolution',120),scale=dpi/72;
  const removeMetadata=panel.querySelector('#remove-metadata').checked;
  const originalMetadata=removeMetadata?null:await pdf.getMetadata().catch(()=>null);
  let out=null;
  for(let i=1;i<=pdf.numPages;i++){
    checkCancelled();
    const page=await pdf.getPage(i),base=page.getViewport({scale:1}),viewport=page.getViewport({scale});
    const orientation=base.width>base.height?'landscape':'portrait',format=[base.width*.352778,base.height*.352778];
    const canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);
    await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;
    if(!out)out=new jsPDF({orientation,unit:'mm',format,compress:true});else out.addPage(format,orientation);
    out.addImage(canvas.toDataURL('image/jpeg',quality),'JPEG',0,0,format[0],format[1],undefined,'FAST');
    canvas.width=canvas.height=1;progress(i/pdf.numPages*92);await yieldFrame();
  }
  if(originalMetadata?.info)out.setProperties({title:originalMetadata.info.Title||'',subject:originalMetadata.info.Subject||'',author:originalMetadata.info.Author||'',keywords:originalMetadata.info.Keywords||'',creator:originalMetadata.info.Creator||''});
  const blob=out.output('blob'),saved=original.size-blob.size,reduced=saved>0;
  const details=`Original ${bytes(original.size)} · Compressed ${bytes(blob.size)} · ${reduced?`${bytes(saved)} saved (${(saved/original.size*100).toFixed(1)}%)`:'Output is not smaller; keep the original if size reduction is your goal'} · ${pdf.numPages} pages · ${panel.querySelector('#compression-mode').selectedOptions[0].text}`;
  panel.querySelector('#operation-result').innerHTML=`${downloadCard(blob,'compressed.pdf',details)}${!reduced?'<div class="disclaimer-box">This PDF was already efficient for the selected settings. No reduction is claimed.</div>':''}`;
  pdf.destroy();progress(100);
}

async function compressImages(){
  const format=panel.querySelector('#output-format').value,quality=numVal('#quality',80)/100,maxW=numVal('#target-width',0),maxH=numVal('#target-height',0);
  const preserve=panel.querySelector('#preserve-ratio').checked,zip=new JSZip(),results=[];
  for(let i=0;i<state.files.length;i++){
    checkCancelled();const file=state.files[i].file,img=await loadImage(file);let w=img.naturalWidth,h=img.naturalHeight;
    if(!preserve){w=maxW||w;h=maxH||h}else{if(maxW&&w>maxW){h*=maxW/w;w=maxW}if(maxH&&h>maxH){w*=maxH/h;h=maxH}}
    w=Math.max(1,Math.round(w));h=Math.max(1,Math.round(h));
    const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);
    const blob=await new Promise(r=>canvas.toBlob(r,format,quality));const ext=format==='image/png'?'png':format==='image/webp'?'webp':'jpg';
    const name=`${safeName(file.name.replace(/\.[^.]+$/,''))}-compressed.${ext}`,larger=blob.size>=file.size;zip.file(name,blob);
    results.push({name,blob,original:file.size,larger,url:blobUrl(blob),w,h});URL.revokeObjectURL(img.src);canvas.width=canvas.height=1;
    progress((i+1)/state.files.length*85);await yieldFrame();
  }
  let batch='';if(results.length>1){const blob=await zip.generateAsync({type:'blob'},m=>progress(85+m.percent*.15)),url=blobUrl(blob);batch=`<a class="tool-button" href="${url}" download="compressed-images.zip">Download all as ZIP</a>`}
  panel.querySelector('#operation-result').innerHTML=`<div class="result-summary"><h3>Compression results</h3>${batch}<div class="preview-grid">${results.map(r=>`<figure><img src="${r.url}" alt="Compressed preview"><figcaption><strong>${escapeHtml(r.name)}</strong><br>${bytes(r.original)} → ${bytes(r.blob.size)} · ${r.w} × ${r.h}${r.larger?'<br><em>Output is larger; keep the original if size is the priority.</em>':''}<br><a href="${r.url}" download="${r.name}">Download</a></figcaption></figure>`).join('')}</div></div>`;progress(100);
}
function numVal(selector,fallback=0){const value=Number(panel.querySelector(selector)?.value);return Number.isFinite(value)?value:fallback}

setTool(new URL(location.href).searchParams.get('tool')||'merge');
