const money = value => `NPR ${Number(value || 0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const pct = value => `${Number(value || 0).toFixed(2)}%`;
const number = value => Number.parseFloat(value) || 0;
const el = (tag, attrs = {}, text = '') => { const node = document.createElement(tag); Object.entries(attrs).forEach(([key,value]) => node.setAttribute(key,value)); if (text) node.textContent = text; return node; };
const field = (label, name, type = 'number', value = '', extra = '') => `<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${value}" ${extra}></div>`;
const select = (label, name, options) => `<div class="field"><label for="${name}">${label}</label><select id="${name}" name="${name}">${options.map(([value,text]) => `<option value="${value}">${text}</option>`).join('')}</select></div>`;
const buttonBar = () => '<div class="tool-actions"><button type="submit">Calculate</button><button type="button" class="secondary" data-reset>Reset</button><button type="button" class="secondary" data-print>Print</button><button type="button" class="secondary" data-csv>Download CSV</button></div>';
const standardNote = standard => `<div class="methodology"><h2>Relevant standard</h2><p class="tool-note">${standard}. This client-side tool separates mathematical calculation from accounting judgment. Inputs and results remain in this browser and are not transmitted.</p><div class="disclaimer-box">These tools are intended for educational and analytical purposes. Results depend on the information and assumptions entered and should not be treated as a substitute for professional judgment or, where applicable, actuarial or valuation advice.</div></div>`;
const formWrap = (title, body) => `<form class="tool-form" id="tool-form">${body}${buttonBar()}</form><p class="tool-error" id="tool-error" role="alert"></p>`;

function scheduleTable(rows, columns) { if (!rows.length) return '<p class="tool-note">Calculate to generate the detailed working.</p>'; return `<div class="table-scroll"><table class="tool-table"><thead><tr>${columns.map(column => `<th>${column[1]}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr>${columns.map(([key]) => `<td>${row[key] ?? ''}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`; }
function downloadCsv(rows) { if (!rows.length) return; const keys = Object.keys(rows[0]); const csv = [keys.join(','), ...rows.map(row => keys.map(key => `"${String(row[key] ?? '').replaceAll('"','""')}"`).join(','))].join('\n'); const link = el('a',{href:URL.createObjectURL(new Blob([csv],{type:'text/csv'})),download:'calculation-working.csv'}); link.click(); URL.revokeObjectURL(link.href); }
function valid(form, required) { const values = Object.fromEntries(new FormData(form)); const missing = required.find(key => !values[key] || number(values[key]) < 0); if (missing) throw new Error(`Please enter a valid value for ${missing.replaceAll('_',' ')}.`); return values; }

const calculators = {
  emi: { title:'EMI Calculator', description:'Reducing-balance instalment calculation with a reconciled amortisation schedule.', standard:'General financial mathematics', fields:`${field('Loan amount','loan_amount','number','1000000','min="0" required')}${field('Annual interest rate (%)','annual_rate','number','8','min="0" step="0.01" required')}<div class="form-row">${field('Loan tenure','tenure','number','5','min="0.01" required')}${select('Tenure unit','tenure_unit',[['years','Years'],['months','Months']])}</div>${select('Payment frequency','frequency',[['12','Monthly'],['4','Quarterly'],['2','Semi-Annual'],['1','Annual']])}${field('Loan start date','start_date','date')}`, required:['loan_amount','annual_rate','tenure'] },
  lease: { title:'NFRS 16 Lease Calculator', description:'Indicative lease liability, ROU asset and schedule calculation using present value mathematics.', standard:'NFRS 16 Leases', fields:`${field('Lease commencement date','start_date','date','','required')}<div class="form-row">${field('Lease term (years)','term_years','number','5','min="0" required')}${field('Lease payment','payment','number','50000','min="0" required')}</div>${select('Payment frequency','frequency',[['12','Monthly'],['4','Quarterly'],['2','Semi-Annual'],['1','Annual']])}${select('Payment timing','timing',[['end','End of period'],['beginning','Beginning of period']])}${field('Annual discount rate (%)','discount_rate','number','8','min="0" step="0.01" required')}${select('Rent escalation','escalation',[['none','None'],['percent','Fixed percentage'],['amount','Fixed amount']])}${field('Escalation rate / amount','escalation_value','number','0','min="0"')}${field('Initial direct costs','direct_costs','number','0','min="0"')}${field('Lease incentives','incentives','number','0','min="0"')}${field('Prepayments','prepayments','number','0','min="0"')}${field('Restoration obligation','restoration','number','0','min="0"')}${field('Residual value guarantee payable','residual','number','0','min="0"')}${field('Purchase option exercise price','purchase_option','number','0','min="0"')}`, required:['start_date','term_years','payment','discount_rate'] },
  eir: { title:'NFRS 9 Effective Interest Rate Calculator', description:'Numerical effective-interest calculation and amortised-cost schedule.', standard:'NFRS 9 Financial Instruments', fields:`${select('Instrument type','instrument',[['asset','Financial asset'],['liability','Financial liability']])}${field('Face value / principal','principal','number','1000000','min="0" required')}${field('Initial transaction amount','initial_amount','number','950000','min="0" required')}${field('Nominal / coupon rate (%)','coupon_rate','number','8','min="0" step="0.01"')}${field('Transaction costs','transaction_costs','number','0','min="0"')}${field('Fees','fees','number','0','min="0"')}${field('Premium / discount','premium_discount','number','0')}${field('Tenure (years)','tenure','number','5','min="0.01" required')}${select('Payment frequency','frequency',[['12','Monthly'],['4','Quarterly'],['2','Semi-Annual'],['1','Annual']])}${field('Maturity / redemption amount','maturity','number','1000000','min="0" required')}`, required:['principal','initial_amount','tenure','maturity'] },
  eps: { title:'NAS 33 EPS Calculator', description:'Basic and diluted EPS with weighted-average share working.', standard:'NAS 33 Earnings per Share', fields:`${select('Mode','mode',[['basic','Basic EPS'],['diluted','Diluted EPS']])}${field('Profit attributable to ordinary holders','profit','number','1000000','required')}${field('Preference dividends / adjustments','preference','number','0')}${field('Opening ordinary shares','opening_shares','number','100000','min="0" required')}${field('Shares issued during period','issued_shares','number','0','min="0"')}${field('Shares repurchased during period','repurchased_shares','number','0','min="0"')}${field('Potential ordinary shares (diluted mode)','potential_shares','number','0','min="0"')}${field('Incremental adjusted earnings','incremental_earnings','number','0','min="0"')}${field('Average market price','market_price','number','0','min="0"')}`, required:['profit','opening_shares'] },
  borrowing: { title:'NAS 23 Borrowing Cost Calculator', description:'Indicative specific and general borrowing-cost capitalisation working.', standard:'NAS 23 Borrowing Costs', fields:`${field('Qualifying expenditure','expenditure','number','1000000','min="0" required')}${field('Capitalisation period (months)','period_months','number','12','min="0" required')}${field('Specific borrowing amount','specific_amount','number','500000','min="0"')}${field('Specific borrowing rate (%)','specific_rate','number','8','min="0"')}${field('Investment income','investment_income','number','0','min="0"')}${field('General borrowing balance','general_balance','number','500000','min="0"')}${field('General borrowing rate (%)','general_rate','number','10','min="0"')}`, required:['expenditure','period_months'] },
  dbo: { title:'NAS 19 Defined Benefit Obligation Calculator', description:'Indicative simplified projected-unit-credit calculation; not an actuarial valuation.', standard:'NAS 19 Employee Benefits', fields:`${field('Current age','current_age','number','35','min="0" required')}${field('Retirement age','retirement_age','number','60','min="0" required')}${field('Current monthly salary','salary','number','100000','min="0" required')}${field('Completed service (years)','service','number','5','min="0" required')}${field('Expected salary growth rate (%)','salary_growth','number','6','min="0"')}${field('Discount rate (%)','discount_rate','number','8','min="0" required')}${field('Expected attrition rate (%)','attrition','number','0','min="0"')}${field('Benefit months per service year','benefit_months','number','1','min="0.01" required')}${field('Vesting period (years)','vesting','number','0','min="0"')}`, required:['current_age','retirement_age','salary','service','discount_rate','benefit_months'] }
};

function makeRows(result, type) {
  if (type === 'emi') return result.rows.map(row => ({ instalment:row.i, date:row.date, opening:money(row.opening), emi:money(row.payment), interest:money(row.interest), principal:money(row.principal), closing:money(row.closing) }));
  if (type === 'lease') return result.rows.map(row => ({ period:row.i, date:row.date, opening:money(row.opening), payment:money(row.payment), finance_cost:money(row.interest), principal:money(row.principal), closing:money(row.closing) }));
  if (type === 'eir') return result.rows.map(row => ({ period:row.i, date:row.date, opening:money(row.opening), cash_interest:money(row.cash), eir_interest:money(row.interest), principal:money(row.principal), amortisation:money(row.amort), closing:money(row.closing) }));
  return [];
}
function calculate(type, values) {
  if (type === 'emi') { const periods = values.tenure_unit === 'years' ? Math.ceil(number(values.tenure)*number(values.frequency)) : Math.ceil(number(values.tenure)*number(values.frequency)/12); const rate = number(values.annual_rate)/100/number(values.frequency); const principal = number(values.loan_amount); const factor = Math.pow(1+rate,periods); const payment = rate ? principal*rate*factor/(factor-1) : principal/periods; let balance=principal, rows=[]; for(let i=1;i<=periods;i++){const interest=balance*rate;const p=i===periods?balance:payment-interest;const closing=Math.max(0,balance-p);rows.push({i,date:values.start_date||'',opening:balance,payment:i===periods?balance+interest:payment,interest,principal:p,closing});balance=closing;} return {metrics:[['EMI',money(payment)],['Total interest',money(rows.reduce((s,r)=>s+r.interest,0))],['Total payment',money(rows.reduce((s,r)=>s+r.payment,0))],['Instalments',periods]],rows}; }
  if (type === 'lease') { const freq=number(values.frequency), periods=Math.ceil(number(values.term_years)*freq), r=(number(values.discount_rate)/100)/freq, payment=number(values.payment), pv=payment*(1-Math.pow(1+r,-periods))/r*(values.timing==='beginning'?1+r:1), rou=pv+number(values.prepayments)+number(values.direct_costs)+number(values.restoration)-number(values.incentives)+number(values.residual)+number(values.purchase_option); let balance=pv, asset=rou, rows=[]; for(let i=1;i<=periods;i++){const interest=balance*r, p=values.timing==='beginning'&&i===1?payment:payment, principal=p-interest, close=Math.max(0,balance-principal);asset=Math.max(0,asset-rou/periods);rows.push({i,date:values.start_date||'',opening:balance,payment:p,interest,principal,closing:close,asset});balance=close;} return {metrics:[['Initial lease liability',money(pv)],['Initial ROU asset',money(rou)],['Contractual payments',money(payment*periods)],['Total finance cost',money(rows.reduce((s,r)=>s+r.interest,0))],['Straight-line depreciation',money(rou/periods)]],rows}; }
  if (type === 'eir') { const freq=number(values.frequency), n=Math.ceil(number(values.tenure)*freq), principal=number(values.principal), maturity=number(values.maturity), initial=number(values.initial_amount)+number(values.transaction_costs)+number(values.fees)+number(values.premium_discount), cash=principal*(number(values.coupon_rate)/100)/freq; let low=-.99, high=1; const npv=r=>cash*(1-Math.pow(1+r,-n))/r+maturity*Math.pow(1+r,-n); for(let j=0;j<80;j++){const mid=(low+high)/2;if(npv(mid)>initial) low=mid; else high=mid;} const rate=(low+high)/2; let balance=initial, rows=[]; for(let i=1;i<=n;i++){const interest=balance*rate, principalFlow=i===n?maturity:0, close=balance+interest-cash-principalFlow;rows.push({i,date:'',opening:balance,cash,interest,principal:principalFlow,amort:interest-cash-principalFlow,closing:close});balance=close;} return {metrics:[['Periodic EIR',pct(rate*100)],['Annual effective rate',pct((Math.pow(1+rate,freq)-1)*100)],['Initial carrying amount',money(initial)],['Total cash interest',money(cash*n)],['Total EIR interest',money(rows.reduce((s,r)=>s+r.interest,0))]],rows}; }
  if (type === 'eps') { const adjusted=number(values.profit)-number(values.preference), shares=number(values.opening_shares)+number(values.issued_shares)-number(values.repurchased_shares), basic=adjusted/shares, incremental=number(values.mode==='diluted'?values.potential_shares:0), dilutive=number(values.incremental_earnings)/Math.max(1,incremental)<basic, diluted=dilutive?(adjusted+number(values.incremental_earnings))/(shares+incremental):basic; return {metrics:[['Adjusted earnings',money(adjusted)],['Weighted ordinary shares',shares.toLocaleString()],['Basic EPS',`NPR ${basic.toFixed(2)} per share`],['Diluted EPS',`NPR ${diluted.toFixed(2)} per share`]],rows:[{item:'Opening shares',value:shares},{item:'Adjusted earnings',value:money(adjusted)},{item:'Dilutive instrument included',value:dilutive?'Yes':'No'}]}; }
  if (type === 'borrowing') { const specific=Math.max(0,number(values.specific_amount)*number(values.specific_rate)/100*number(values.period_months)/12-number(values.investment_income)), general=number(values.general_balance)*number(values.general_rate)/100*number(values.period_months)/12, total=Math.min(number(values.expenditure),specific+general); return {metrics:[['Specific borrowing cost',money(specific)],['Weighted general rate',pct(number(values.general_rate))],['General borrowing cost',money(general)],['Total capitalised',money(total)],['Borrowing cost expensed',money(Math.max(0,specific+general-total))]],rows:[{item:'Qualifying expenditure',value:money(values.expenditure)},{item:'Specific cost net of investment income',value:money(specific)},{item:'General borrowing cost',value:money(general)},{item:'Capitalised',value:money(total)}]}; }
  if (type === 'dbo') {
    const currentAge = number(values.current_age);
    const retirementAge = number(values.retirement_age);
    if (retirementAge <= currentAge) throw new Error('Retirement age must be greater than current age.');
    const years = retirementAge - currentAge;
    const salary = number(values.salary) * Math.pow(1 + number(values.salary_growth) / 100, years);
    const service = number(values.service) + years;
    const benefit = salary * number(values.benefit_months) * service;
    const probability = Math.pow(1 - number(values.attrition) / 100, years);
    const factor = Math.pow(1 + number(values.discount_rate) / 100, -years);
    const dbo = benefit * probability * factor;
    return {metrics:[['Projected salary at retirement',money(salary * 12)],['Projected service',`${service.toFixed(2)} years`],['Projected benefit',money(benefit)],['Probability adjustment',pct(probability * 100)],['Discount factor',factor.toFixed(6)],['Estimated DBO',money(dbo)]],rows:[{item:'Projected benefit',value:money(benefit)},{item:'Probability adjustment',value:pct(probability * 100)},{item:'Discount factor',value:factor.toFixed(6)},{item:'Estimated DBO',value:money(dbo)}]};
  }
}
function renderCalculator(type, host) {
  const config = calculators[type];
  host.innerHTML = `<div class="tool-layout"><section class="tool-panel"><h2>Inputs</h2>${formWrap(config.title, config.fields)}</section><section class="tool-panel"><h2>Results</h2><div class="result-box" id="results"><h3>Enter assumptions</h3><p class="tool-note">Calculate to see the result and detailed working.</p></div></section></div><section class="working"><h2>Detailed working</h2><div id="working"><p class="tool-note">The schedule will appear after calculation.</p></div></section>${standardNote(config.standard)}`;
  let result = {rows: []};
  const form = host.querySelector('#tool-form');
  const show = () => {
    try {
      result = calculate(type, Object.fromEntries(new FormData(form)));
      host.querySelector('#tool-error').textContent = '';
      host.querySelector('#results').innerHTML = `<h3>Indicative result</h3><div class="result-grid">${result.metrics.map(([label, value]) => `<div class="result-item"><span>${label}</span><strong>${value}</strong></div>`).join('')}</div>`;
      const columns = type === 'emi'
        ? [['instalment','Instalment'],['date','Payment date'],['opening','Opening principal'],['emi','EMI'],['interest','Interest'],['principal','Principal'],['closing','Closing principal']]
        : type === 'lease'
          ? [['period','Period'],['date','Payment date'],['opening','Opening liability'],['payment','Lease payment'],['interest','Finance cost'],['principal','Principal'],['closing','Closing liability']]
          : type === 'eir'
            ? [['period','Period'],['date','Date'],['opening','Opening amortised cost'],['cash_interest','Cash interest'],['eir_interest','EIR interest'],['principal','Principal cash flow'],['amortisation','Amortisation'],['closing','Closing amount']]
            : [['item','Working'],['value','Amount']];
      host.querySelector('#working').innerHTML = scheduleTable(makeRows(result, type), columns);
    } catch (error) {
      host.querySelector('#tool-error').textContent = error.message;
    }
  };
  form.addEventListener('submit', event => { event.preventDefault(); show(); });
  host.querySelector('[data-reset]').addEventListener('click', () => { form.reset(); host.querySelector('#results').innerHTML = '<h3>Enter assumptions</h3><p class="tool-note">Calculate to see the result and detailed working.</p>'; host.querySelector('#working').innerHTML = '<p class="tool-note">The schedule will appear after calculation.</p>'; });
  host.querySelector('[data-print]').addEventListener('click', () => window.print());
  host.querySelector('[data-csv]').addEventListener('click', () => downloadCsv(makeRows(result, type)));
}

const decisions = {
  'lease-identification': {title:'NFRS 16 Lease Identification', standard:'NFRS 16 Leases', questions:['Is there an identified asset, explicitly or implicitly specified?','Does the supplier have substantive substitution rights?','Does the customer obtain substantially all economic benefits from use?','Does the customer have the right to direct how and for what purpose the asset is used?'], result:a=>a[0]==='no'||a[2]==='no'||a[3]==='no'?'Arrangement may not contain a lease':a.includes('unsure')||a[1]==='yes'?'Further assessment required':'Arrangement may contain a lease'},
  'financial-asset-classification': {title:'NFRS 9 Financial Asset Classification',standard:'NFRS 9 Financial Instruments',questions:['Is the instrument a debt instrument?','For a debt instrument, is the business model hold to collect?','Do contractual cash flows meet the SPPI characteristics?','If not hold to collect, is the business model hold to collect and sell?'], result:a=>a[0]==='no'?'Further assessment required':a[1]==='yes'&&a[2]==='yes'?'Amortised Cost':a[3]==='yes'&&a[2]==='yes'?'FVOCI':a.includes('unsure')?'Further assessment required':'FVTPL'},
  'impairment-indicators': {title:'NAS 36 Impairment Indicator Assessment',standard:'NAS 36 Impairment of Assets',questions:['Is there a significant decline in market value or an adverse external change?','Is the asset obsolete, physically damaged or becoming idle?','Is economic performance worse than expected?','Are there adverse legal, technological, economic or interest-rate changes?'],result:a=>a.includes('yes')?'One or more impairment indicators identified':a.includes('unsure')?'Further assessment required':'No impairment indicators identified from responses'},
  'provision-assessment': {title:'NAS 37 Provision Assessment',standard:'NAS 37 Provisions, Contingent Liabilities and Contingent Assets',questions:['Has a past event occurred?','Does it create a present legal or constructive obligation?','Is an outflow of resources probable?','Can the obligation be reliably estimated?'],result:a=>a[0]==='yes'&&a[1]==='yes'&&a[2]==='yes'&&a[3]==='yes'?'Provision may be required':a.includes('unsure')?'Further assessment required':a[0]==='yes'&&a[1]==='yes'?'Potential contingent liability':'No provision indicated from responses'},
  'subsequent-events': {title:'NAS 10 Subsequent Events Assessment',standard:'NAS 10 Events after the Reporting Period',questions:['Did the event occur after the reporting date?','Did it occur before the financial statements were authorised for issue?','Does it provide evidence of conditions existing at the reporting date?','Is the event material or relevant to going concern?'],result:a=>a[2]==='yes'?'Potential adjusting event':a[3]==='yes'&&a[0]==='yes'?'Potential material non-adjusting event':a.includes('unsure')?'Further assessment required':'Potential non-adjusting event'},
  'related-party': {title:'NAS 24 Related Party Assessment',standard:'NAS 24 Related Party Disclosures',questions:['Does a person or entity have control, joint control or significant influence?','Is the party key management personnel or a close family member?','Is the entity a parent, subsidiary, fellow subsidiary, associate or joint venture?','Could the same third party create a related relationship?'],result:a=>a.includes('yes')?'Potential related party':a.includes('unsure')?'Further assessment required':'No related-party relationship identified from responses'},
  'control-assessment': {title:'NFRS 10 Control Assessment',standard:'NFRS 10 Consolidated Financial Statements',questions:['Does the investor have substantive rights giving current ability to direct relevant activities?','Is the investor exposed or entitled to variable returns?','Can the investor use power to affect those returns?','Could protective rights, agency or structured-entity factors change the assessment?'],result:a=>a[0]==='yes'&&a[1]==='yes'&&a[2]==='yes'&&a[3]!=='yes'?'Control may exist':a.includes('unsure')||a[3]==='yes'?'Further assessment required':'Control may not exist'},
  'principal-agent': {title:'NFRS 15 Principal vs Agent Assessment',standard:'NFRS 15 Revenue from Contracts with Customers',questions:['Does the entity have primary responsibility for fulfilment?','Does the entity bear inventory or fulfilment risk?','Does the entity have pricing discretion?','Does the entity control the specified good or service before transfer?'],result:a=>a[3]==='yes'&&a.filter(x=>x==='yes').length>=2?'Entity may be Principal':a.includes('unsure')?'Further assessment required':'Entity may be Agent'}
};
function renderDecision(type,host){const config=decisions[type];let step=0,answers=[];host.innerHTML=`<section class="tool-panel"><div class="decision-progress"><span></span></div><p class="tool-note" id="step-label"></p><h2 class="decision-question" id="question"></h2><div class="choice-list" id="choices"><label><input type="radio" name="choice" value="yes"> Yes</label><label><input type="radio" name="choice" value="no"> No</label><label><input type="radio" name="choice" value="unsure"> Not sure</label></div><p class="tool-error" id="decision-error" role="alert"></p><div class="tool-actions"><button type="button" id="previous" class="secondary">Previous</button><button type="button" id="next">Next</button><button type="button" id="restart" class="secondary">Restart</button></div></section><section class="methodology"><h2>Relevant standard</h2><p class="tool-note">${config.standard}. Based on the information entered, this decision-support result is indicative and does not replace professional judgment.</p><div class="disclaimer-box">Further assessment may be required where facts are incomplete, rights are substantive, or the standard requires judgment.</div></section>`;const paint=()=>{host.querySelector('#step-label').textContent=`Step ${step+1} of ${config.questions.length}`;host.querySelector('#question').textContent=config.questions[step];host.querySelector('.decision-progress span').style.width=`${(step/config.questions.length)*100}%`;host.querySelectorAll('input').forEach(input=>input.checked=input.value===answers[step]);host.querySelector('#previous').disabled=step===0;host.querySelector('#next').textContent=step===config.questions.length-1?'Show result':'Next';};const finish=()=>{const outcome=config.result(answers);host.querySelector('.tool-panel').innerHTML=`<div class="decision-result"><p class="eyebrow">Indicative result</p><h3>${outcome}</h3><p>Based on the information entered, this is an indicative decision-support outcome.</p><h4>Why?</h4><p>Key factors from your answers were considered across the control, obligation, economic-benefit or contractual-term questions above.</p></div><div class="tool-actions"><button type="button" id="restart">Restart</button></div>`;host.querySelector('#restart').addEventListener('click',()=>{step=0;answers=[];renderDecision(type,host);});};host.querySelector('#next').addEventListener('click',()=>{const selected=host.querySelector('input:checked');if(!selected){host.querySelector('#decision-error').textContent='Choose an answer before continuing.';return;}answers[step]=selected.value;if(step===config.questions.length-1)finish();else{step++;paint();}});host.querySelector('#previous').addEventListener('click',()=>{if(step){step--;paint();}});host.querySelector('#restart').addEventListener('click',()=>{step=0;answers=[];paint();});paint();}
const host=document.querySelector('[data-tool]'); if(host){const type=host.dataset.tool;if(calculators[type])renderCalculator(type,host);else if(decisions[type])renderDecision(type,host);}
